### PR TITLE
Add StandardTimeLogger

### PR DESCRIPTION
**Pull request by pellaeon**
StandardTimeLogger is StandardLogger with custom time format

### CODE REVIEW

**Comment by TheMue** [comment]
Thx, will merge it here and also to the new Go library (github.com/tideland/golib). Is it possible to check for a valid time format in the constructor?

**Comment by TheMue** [comment]
Took a deeper look. I'll add a solution with less code duplication to github.com/tideland/golib/logger.

**Comment by TheMue** [comment]
Added it to new golib, see https://godoc.org/github.com/tideland/golib/logger#NewTimeformatLogger.

**Comment by pellaeon** [comment]
Yeah, yours is more efficient, thanks!

**Pull request closed without merging**
